sudo: false
language: python

python:
 - "2.7"

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     #- gcc-6
     #- g++-6
     #- gfortran-6
     #- libhdf5-serial-dev
     # libtool is needed by libint
     #- libtool
     # libstdc++6 is needed to build a recent cppcheck
     - libstdc++6
     # libpcre3-dev is needed to build a recent cppcheck
     - libpcre3-dev
     

env:
  global:
     #- QAWORKDIR=$HOME/qaworkdir
     #- CACHED=$QAWORKDIR/cached
     #- PIP_WHEEL_DIR=$CACHED/wheels
     #- PIP_FIND_LINKS=file://$CACHED/wheels
     #- PIP_NO_CACHE_DIR=no
     #- CXX="g++-6"
     #- CC="gcc-6"
     #- FC="gfortran-6"
     - VERSION=1.83
     - NAMEVER=cppcheck-${VERSION}
     - CACHED=$HOME/cached 

cache:
  directories:
     - $CACHED
     
install:
  - bash ./cppcheck.sh

script:
 - ls -R
 #- cd $HOME && ls -R
 - ${CACHED}/${NAMEVER}/cppcheck --version
 
