sudo: false
language: python

python:
 - "2.7"

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - gcc-6
     - g++-6
     #- gfortran-6
     #- libhdf5-serial-dev
     # libtool is needed by libint
     - libtool
     # libpcre3-dev is needed to build a recent cppcheck
     - libpcre3-dev

env:
  global:
     #- QAWORKDIR=$HOME/qaworkdir
     #- CACHED=$QAWORKDIR/cached
     #- PIP_WHEEL_DIR=$CACHED/wheels
     #- PIP_FIND_LINKS=file://$CACHED/wheels
     #- PIP_NO_CACHE_DIR=no
     - CXX="g++-6"
     - CC="gcc-6"
     - FC="gfortran-6"

cache:
  directories:
    - $HOME/cached
    - ./cached

install:
  - bash ./cppcheck.sh

script:
 - ls -R
 - ./cached/cppcheck-1.72
 - ${CACHED}/${NAMEVER} --version
